### PR TITLE
Fix notices2 getters

### LINKED ISSUE #170: SnapdNotice getters return references
The getters in SnapdNotice return references (e.g. `snapd_notice_get_last_repeated`). This isn't necessary (the object is not created and is owned by the object) and doesn't match the style of the other objects (and GObject code in general). This is a risk on the API user who might forget to release the reference and requires more boilerplate code for simple cases.

It would be nice if we correct this, I see two options:
- Make new getters and deprecate the old ones, e.g. `snapd_notice_get_last_repeated2`. It's a little ugly but works.
- Make a new object SnapdNotice2 that has new methods. More work than the above and even more messy.

### PR DESCRIPTION
**Pull request by sergio-costas**
Several getters were returning a reference of the data instead of just a pointer; this is, they incremented the refcount of the returned element. This isn't what the rest of the API does, so for uniformity, this PR adds new versions of the getters and deprecates the old ones.
    
Fix #170

### CODE REVIEW

File: snapd-glib/snapd-notice.c [hunk 1]
```diff
@@ -143,6 +143,7 @@ snapd_notice_get_key (SnapdNotice *self)
  * Returns: (transfer container): a HashTable with the data elements.
  *
  * Since: 1.65
+ * Deprecated: 1.66
```
Comment (robert-ancell) [inline snapd-glib/snapd-notice.c:146]: Should be:
```
Deprecated: 1.66: Use snapd_notice_get_last_data2()
```

File: snapd-glib/snapd-notice.c [hunk 2]
```diff
@@ -170,6 +189,25 @@ snapd_notice_get_first_occurred (SnapdNotice *self)
...
+ * Returns: (transfer none): a #GDateTime.
+ *
+ * Since: 1.66
+ */
+GDateTime *
+snapd_notice_get_first_occurred2 (SnapdNotice *self)
+{
+    g_return_val_if_fail (SNAPD_IS_NOTICE (self), NULL);
+    if (self->first_occurred == NULL)
+        return NULL;
```
Comment (robert-ancell) [inline snapd-glib/snapd-notice.c:207]: This doesn't do anything - it would have returned NULL in the next line anyway!

File: snapd-qt/notice.cpp [hunk 3]
```diff
@@ -60,17 +60,17 @@ static QDateTime convertDateTime (GDateTime *datetime)
 
 QDateTime QSnapdNotice::firstOccurred () const
 {
-    return convertDateTime ((GDateTime*) snapd_notice_get_first_occurred (SNAPD_NOTICE (wrapped_object)));
+    return convertDateTime ((GDateTime*) snapd_notice_get_first_occurred2 (SNAPD_NOTICE (wrapped_object)));
```
Comment (robert-ancell) [inline snapd-qt/notice.cpp:63]: These casts shouldn't be necessary, right?

**Review by robert-ancell — APPROVED** [review]
Other than the above comments looks good, thanks!

File: snapd-glib/snapd-notice.c (hunk 1 above)
Comment (sergio-costas) [reply snapd-glib/snapd-notice.c]: Fixed!

File: snapd-glib/snapd-notice.c (hunk 2 above)
Comment (sergio-costas) [reply snapd-glib/snapd-notice.c]: Ops!!!! Yes, it was the check to avoid errors when calling XXX_ref. The problems of copy&paste 😅

File: snapd-qt/notice.cpp (hunk 3 above)
Comment (sergio-costas) [reply snapd-qt/notice.cpp]: Mmm... yes, they aren't needed anymore. I added there when the return value was `const GDateTime*`, so they were required, but now they aren't. Fixed.

**Review by robert-ancell — APPROVED** [review]
